name: golangci-lint
on:
  push:
  pull_request:
  
jobs:
  golangci:
    name: Lint Sourcecode
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
          args: --timeout 240
